
-- CREATE OR USE A DATABASE
USE ALPHA;

-- CREATE A SCHEMA 
CREATE SCHEMA EXP1

-- A BUCKET SHOULD BE CREATED OR EXIST 
-- AN APPROPRIATE IAM ROLE SHOULD BE THERE (OR TO BE CREATED IN AWS )
-- THE ROLE SHOULD BE CREATED IN ORDER TO ACCESS THE SNOWFLAKE 
-- COPY THE ARN 

-- WE NEED TO CREATE THE INTEGRATION OBJECT . IT WILL ENABLE THE HANDSHAKE BETWEEN AWS AND SNOWFLAKE 

CREATE OR REPLACE STORAGE INTEGRATION s3_int
       TYPE = EXTERNAL_STAGE
       STORAGE_PROVIDER = 'S3'
       ENABLED = TRUE
       STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::925950898902:role/snowflake_aws'
       STORAGE_ALLOWED_LOCATIONS = ('s3://suyallearningsnowflake/')


SHOW INTEGRATIONS;

DESC INTEGRATION s3_int; 

-- NOTE 
--     STORAGE_AWS_IAM_USER_ARN :  arn:aws:iam::548099410567:user/externalstages/ciy1b00000
--     STORAGE_AWS_EXTERNAL_ID  : OX56784_SFCRole=2_4R9Tosr2Sd61Zis1rFvgBPYUPws=

-- NOw using this , edit the IAM role in AWS (edit the policy)
                         
-- PROVIDE GRANT TO THE ROLE (IT SHOULD BE DIFFERENT FROM ACCOUNTADMIN)
GRANT USAGE ON INTEGRATION s3_int TO ROLE ACCOUNTADMIN;

                         
CREATE OR REPLACE FILE FORMAT EXP1.my_csv_file_format
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1;


-- CREATE THE STAGE 

CREATE OR REPLACE STAGE my_aws_csv_stage
       STORAGE_INTEGRATION = s3_int
       URL = 's3://suyallearningsnowflake/csv_data/'
       FILE_FORMAT = EXP1.my_csv_file_format;

LIST @my_aws_csv_stage;

DESCRIBE STAGE my_aws_csv_stage;
-- DIRECTORY TABLE (NOT A SEPERATE SNOWFLAKE OBJECT BUT RATHER IMPLICITELY ATTACHED WITH STAGE , NEED TO ENABLE )
       
ALTER STAGE my_aws_csv_stage
   SET DIRECTORY = (ENABLE = TRUE );

-- TO REFLECT THE CHANGE NEEDS TO REFRESH    
ALTER STAGE my_aws_csv_stage REFRESH;

SELECT * FROM DIRECTORY(@my_aws_csv_stage)

       