-- FOR THIS EXERCISE WE ARE CREATING A NEW DATABASE AS STREAMS 
CREATE DATABASE STREAMS;

-- USING THIS DATABASE 
USE STREAMS;

-- CREATING A SCHEMA UNDER THIS DATABASE 
CREATE SCHEMA STREAM_AWS;

-- CREATING A NEW STORAGE INTEGRATION 
CREATE STORAGE INTEGRATION AWS_STORAGE_INT_PIPE
       TYPE = EXTERNAL_STAGE
       STORAGE_PROVIDER = 'S3'
       ENABLED = TRUE 
       STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::925950898902:role/snowflake_aws'
       STORAGE_ALLOWED_LOCATIONS = ('s3://snowpipeinjestdata/injestdir/');

-- QUERING THE STORAGE INTEGRATION OBJECT TO GET THE AWS ARN AND EXTERNAL_ID 
DESC INTEGRATION AWS_STORAGE_INT_PIPE;     
-- STORAGE_AWS_IAM_USER_ARN =  arn:aws:iam::548099410567:user/externalstages/ciy1b00000
-- STORAGE_AWS_EXTERNAL_ID = OX56784_SFCRole=2_okTfWl7I1w4av0dUKKquVnzQYhA=


-- CREATING A NEW STAGE 
CREATE STAGE MY_S3_PIPE_STAGE
URL = 's3://snowpipeinjestdata/injestdir/'
STORAGE_INTEGRATION = AWS_STORAGE_INT_PIPE

-- ALTERING THE STAGE TO ENABLE THE DIRECTORY TABLE 
ALTER STAGE MY_S3_PIPE_STAGE
SET DIRECTORY = (ENABLE = TRUE )

-- LISTING THE STAGE FILES 
LIST @MY_S3_PIPE_STAGE


-- NEED TO REFRESH THE STAGE TO REFLECT THE NEW FILES IN THE DIRECTORY TABLE 
ALTER STAGE MY_S3_PIPE_STAGE REFRESH;

-- SELECTING FROM THE DIRECTORY TABLE 
SELECT * FROM DIRECTORY (@MY_S3_PIPE_STAGE)

-------------------------------------------------------------------------------

--  PIPE CREATION 

--  NOTE :: BEFORE CREATING A PIPE WE SHOULD HAVE SOME TABLE WHICH WILL BE POPULTAED WITH THE FILE DATA 

--  LETS CREATE A TABLE , BASED ON OUR INGESTED FILE
CREATE OR REPLACE TABLE CUSTOMERS
(   CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(50)
);

--      **** CREATE A SNOWPIPE *** 
CREATE OR REPLACE PIPE MY_SNOWPIPE
    AUTO_INGEST=TRUE 
    AS 
    COPY INTO CUSTOMERS 
    FROM @MY_S3_PIPE_STAGE
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);


SHOW PIPES;


-- MANUALLY REFRESH THE PIPE (ALTERNATIVE WE NEED TO ENABLE THE EVENT NOTIFICATION IN AWS )
ALTER PIPE MY_SNOWPIPE REFRESH;


-- LETS CHECK OUR TARGET TABLE 
SELECT * FROM CUSTOMERS;
SELECT COUNT(*) FROM CUSTOMERS;  -- 21

-- SIMULATION 

-- KEEP ADDING NEW FILES IN AWS S3 , AND REFRESH THE PIPE . THE TABLE WILL BE APPENDED WITH THE DATA  