-- START IMPLEMENTING SNOWPIPE 
-- CREATING SEPERATE DATABASE FOR SNOWPIPE 

CREATE OR REPLACE DATABASE SNOWPIPE_DB;
USE SNOWPIPE_DB;

CREATE OR REPLACE SCHEMA SNOWPIPE_DB.EXTERNAL_STAGES;

CREATE OR REPLACE STAGE SNOWPIPE_DB.EXTERNAL_STAGES.PIPE_STAGE 
  STORAGE_INTEGRATION = azure_integration
  URL = ('azure://azuresnowflakecoupling.blob.core.windows.net/snowflakelearning')
  FILE_FORMAT = MANAGE_DB.PUBLIC.FLEFORMAT_AZURE;

LIST @SNOWPIPE_DB.EXTERNAL_STAGES.PIPE_STAGE;

-- WILL CREATE SEPERATE SCHEMA FOR THE STREAMED DATA 
CREATE OR REPLACE SCHEMA SNOWPIPE_DB.STREAM_DATA;

CREATE OR REPLACE TABLE SNOWPIPE_DB.STREAM_DATA.EMP_DATA
(
EMPNO STRING,
ENAME STRING,
JOB STRING,
MGR STRING,
HIREDATE string,
SAL STRING,
COMM STRING,
DEPTNO STRING,
UPDATED_DATE string
);  
-- INITIALLY THE TABLE IS EMPTY 
SELECT * FROM SNOWPIPE_DB.STREAM_DATA.EMP_DATA;

-- TESTING THE SELECT COMMAND FROM STAGE 
SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9 FROM @SNOWPIPE_DB.EXTERNAL_STAGES.PIPE_STAGE 

-- CREATING AND TESTING THE COPY COMMAND 
COPY INTO SNOWPIPE_DB.STREAM_DATA.EMP_DATA
from (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9 FROM @SNOWPIPE_DB.EXTERNAL_STAGES.PIPE_STAGE)

-- CHECK THE DATA IN TABLE 
SELECT * FROM SNOWPIPE_DB.STREAM_DATA.EMP_DATA

-- OKEY COPY COMMAND LOOKS FILE , EMPTY THE TABLE 
DELETE FROM SNOWPIPE_DB.STREAM_DATA.EMP_DATA

-- CREATE PIPE OBJECT IN SEPERATE SCHEMA 
CREATE OR REPLACE SCHEMA SNOWPIPE_DB.SNOWPIPE;

-- CREATE PIPE 
CREATE OR REPLACE PIPE transaction_pipe
AUTO_INGEST = FALSE
AS
COPY INTO SNOWPIPE_DB.STREAM_DATA.EMP_DATA
FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9 FROM @SNOWPIPE_DB.EXTERNAL_STAGES.PIPE_STAGE)
FILE_FORMAT = MANAGE_DB.PUBLIC.FLEFORMAT_AZURE
ON_ERROR = 'CONTINUE';

-- CHECK THE TABLE ONCE IF DATA IS THERE 
SELECT *  FROM SNOWPIPE_DB.STREAM_DATA.EMP_DATA

-- VALIDATION PART 
USE SNOWPIPE_DB.SNOWPIPE;
SHOW PIPES;

DESCRIBE PIPE transaction_pipe

-- *******************************************************************************************
--                       ALTER PIPE <PIPENAME> REFRESH  (as auto refresh is set to false )
-- *******************************************************************************************
ALTER PIPE transaction_pipe REFRESH

-- *******************************************************************************************

-- CHECK PIPE STATUS
SELECT system$pipe_status('transaction_pipe')

-- VALIDATION 

SELECT COUNT(*) FROM SNOWPIPE_DB.STREAM_DATA.EMP_DATA; -- 33



