//////////////////////////   TIME TRAVEL  ////////////////////////////////////////////////////////

CREATE OR REPLACE DATABASE TIMETRAVEL; 

CREATE OR REPLACE SCHEMA EXTERNAL_STAGES; 

CREATE OR REPLACE STAGE TIMETRAVEL.EXTERNAL_STAGES.TIMETRAVEL_STAGE 
URL = 'azure://azuresnowflakecoupling.blob.core.windows.net/timetravel'
STORAGE_INTEGRATION = azure_integration
FILE_FORMAT = MANAGE_DB.PUBLIC.FLEFORMAT_AZURE;

LIST @TIMETRAVEL.EXTERNAL_STAGES.TIMETRAVEL_STAGE;     

CREATE OR REPLACE SCHEMA EMP_SENSITIVE_DATA;

CREATE OR REPLACE TABLE TIMETRAVEL.EMP_SENSITIVE_DATA.EMP_DATA
(
EMPNO STRING,
ENAME STRING,
JOB STRING,
MGR STRING,
HIREDATE string,
SAL STRING,
COMM STRING,
DEPTNO STRING,
UPDATED_DATE string
);  

COPY INTO TIMETRAVEL.EMP_SENSITIVE_DATA.EMP_DATA
FROM @TIMETRAVEL.EXTERNAL_STAGES.TIMETRAVEL_STAGE
FILES = ('emp.csv')

SELECT * FROM TIMETRAVEL.EMP_SENSITIVE_DATA.EMP_DATA;


UPDATE TIMETRAVEL.EMP_SENSITIVE_DATA.EMP_DATA
SET ENAME = 'MUKESH'

-- 1 OFFSET 
SELECT * FROM TIMETRAVEL.EMP_SENSITIVE_DATA.EMP_DATA AT (OFFSET => -60*2)



-- 2 TIMESTAMP 
SELECT CURRENT_TIMESTAMP; -- 2023-05-30 00:09:21.088 -0700

SELECT * FROM TIMETRAVEL.EMP_SENSITIVE_DATA.EMP_DATA BEFORE (TIMESTAMP => '2023-05-30 07:06:20.070'::TIMESTAMP)

ALTER SESSION SET TIMEZONE = 'UTC'
SELECT CURRENT_TIMESTAMP; -- 2023-05-30 00:13:20.290 -0700  2023-05-30 07:13:48.965 +0000


-- 3 USING QUERYID

UPDATE TIMETRAVEL.EMP_SENSITIVE_DATA.EMP_DATA
SET ENAME = 'MUKESH SUYAL'; -- QUERY ID : 01aca093-0001-2059-0003-f92200016142 

SELECT * FROM TIMETRAVEL.EMP_SENSITIVE_DATA.EMP_DATA;
SELECT * FROM TIMETRAVEL.EMP_SENSITIVE_DATA.EMP_DATA BEFORE (STATEMENT => '01aca093-0001-2059-0003-f92200016142')

